name: Creacion de una Rama

on: create

jobs:
  run_create_branch:
      runs-on: ubuntu-latest
      env:
          REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubtest'
              if: always()

            - uses: actions/checkout@v2

            - name: NombreRama
              run: echo ${GITHUB_REF##*/}
              id: name_branch

            - name: create-issue
              id: issue
              uses: alialaa/issue-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: Create Branch ${GITHUB_REF##*/}
                body: It was create branch - ${GITHUB_REF##*/} -
                assignees: |
                  NelsonFonseca

            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#githubtest'
              if: always()