name: Creacion de una Rama

on: create

jobs:
  run_create_branch:
      runs-on: ubuntu-latest
      env:
          REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubtest'
              if: always()

            - uses: actions/checkout@v2

            - name: Inicio
              id: Se creo una rama
              run: echo 'Se ha creado una rama! ${{ steps.extract_branch.outputs.branch }}'

            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#githubtest'
              if: always()