name: Creacion de una Rama

on: create

jobs:
  run_create_branch:
      runs-on: ubuntu-latest
      env:
          REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubtest'
              if: always()

            - uses: actions/checkout@v2

            - name: NombreRama
              run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
              id: name_branch
            - run: echo '${{ steps.extract_branch.outputs.branch }}'

            - name: trello
              uses: awais786327/ifttt-action@v1
              id: trello
              with:
                event: "github_create"
                key: "Gc70Dua-JBnrZCo44v153wsmtaGv40JqvVivB69YbaIECmOyTDfQ6R67zoJtvkly"

            - name: Send email
              uses: devellany/send-mail@v1.0.2
              id: mail
              with:
                host: smtp.google.com
                # Optional port (defaults to 465)
                port: 465
                account: nelsonfonseca80@gmail.com
                password: Zero5inco
                sender: nelson
                from: nelsonfonseca80@gmail.com
                to: nelsonfonseca80@gmail.com
                subject: Branch created ${{ steps.extract_branch.outputs.branch }}
                body: "prueba :)"

            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#githubtest'
              if: always()