name: Creacion de una Rama

on: create

jobs:
  run_create_issue:
      runs-on: ubuntu-latest
      env:
          REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#branches'
              if: always()

            - uses: actions/checkout@v2

            - name: NombreRama
              run: echo ${{ github.ref }}
              id: name_branch

            - name: create-issue
              id: issue
              uses: alialaa/issue-action@v1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
                title: Create Branch ${{ github.ref }}
                body: It was create branch - ${{ github.ref }} -
                assignees: |
                  NelsonFonseca

            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#githubtest'
              if: always()
          
  run_create_card:
    runs-on: ubuntu-latest
    needs: run_create_issue
    env:
        REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
        IMAGE_NAME: ${{ github.repository }}/alerta-cli
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#branches'
        if: always()

      - uses: actions/checkout@v2

      - name: Call trello-github-actions
        id: trello-action
        uses: jessicazu/trello-github-actions@v1.0
        with:
          trello-action: create_card_when_issue_opened 
        env:
          TRELLO_API_KEY: ${{ secrets.TRELLO_KEY }}
          TRELLO_API_TOKEN: ${{ secrets.TRELLO_TOKEN }}
          TRELLO_BOARD_ID: ${{ secrets.TRELLO_BOARD_ID }}
          TRELLO_LIST_ID: ${{ secrets.TRELLO_LIST_ID }} 

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#githubtest'
        if: always()