name: test github actions

on: push

jobs: 
    run_push:
        runs-on: ubuntu-latest
        env:
          REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: 'https://hooks.slack.com/services/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'
        steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubtest'
              if: always()
            - uses: actions/checkout@v2
            - name: Usar node js
              uses: actions/setup-node@v1
              with: 
                node-version: 6
            - name: Intalar dependencias
              id: Compilacion
              run: npm install
            #- name: Correr test unitarios
              #id: Pruebas unitarias
             # run: npm test
            - name: Hacer build
              run: npm run build
            - name: Creación de artefacto
              id: Generar_Artefacto
              uses: actions/upload-artifact@v1
              with:
                name: dist
                path: dist
            - name: Build and push Docker images
              id: Dockerizacion
              uses: docker/build-push-action@v1
              with:
                username: nfonse4
                password: Cc1057609393
                repository: nfonse4/gitactions
                tags: latest
            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#githubtest'
              if: always()