name: test github actions

on: push

jobs: 
    run_push:
        runs-on: ubuntu-latest
        env:
          REPOSITORY_URL: https://github.com/NelsonFonseca/GitActions
          IMAGE_NAME: ${{ github.repository }}/alerta-cli
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

        steps:
            - uses: act10ns/slack@v1
              with:
                status: starting
                channel: '#githubtest'
              if: always()

            - uses: actions/checkout@v2

            - name: Usar node js
              uses: actions/setup-node@v1
              with: 
                node-version: 6

            - name: Instalar dependencias
              id: Compilacion
              run: npm install

            #- name: Correr test unitarios
             # id: Pruebas_Unitarias
              #run: npm test

            - name: Analisis de codigo estatico
              id: Analisis_Codigo_Estatico
              uses: sonarsource/sonarcloud-github-action@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

            - name: Hacer build
              run: npm run build

            - name: Creación de artefacto
              id: Generar_Artefacto
              uses: actions/upload-artifact@v2
              with:
                name: GithubActions
                path: dist

            - name: Dockerizacion
              id: Dockerizacion
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.USER_DOCKER }}
                password: ${{ secrets.PASSWORD_DOCKER }}
                repository: ${{ secrets.REPOSITORY_DOCKER }}
                tags: latest

            - uses: act10ns/slack@v1
              with:
                status: ${{ job.status }}
                steps: ${{ toJson(steps) }}
                channel: '#githubtest'
              if: always()