name: test github actions

on: push

jobs: 
    run_push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Usar node js
              uses: actions/setup-node@v1
              with: 
                node-version: 6
            - name: Intalar dependencias
              run: npm install
            #- name: Correr test unitarios
             # run: npm test
            #- name: Creación de artefacto
             # uses: actions/upload-artifact@v1
              #with:
               # name: dist
                #path: dist
            - name: Reporte Slack
              uses: drilonrecica/action-slack-notify@0.0.3
              env:
                SLACK_CHANNEL: githubtest
                SLACK_WEBHOOK: https://hooks.slack.com/services/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
                SLACK_TITLE: 'Creacion Artefacto'
                SLACK_MESSAGE: 'Esto es una demo :)'
            - name: Build and push Docker images
              uses: docker/build-push-action@v1
              with:
                username: nfonse4
                password: Cc1057609393
                repository: nfonse4/gitactions
                tags: latest